import { Feather } from '@expo/vector-icons';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { useColors } from '@/hooks/useColors';
import { useGhost, formatFocus } from '@/context/GhostContext';
import { Panel } from '@/components/Panel';
import { Screen, SectionLabel, TextLabel } from '@/components/Screen';

const dayNames = ['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT'];
const getDayKey = (date: Date) => date.toISOString().slice(0, 10);

export default function IntelScreen() {
  const colors = useColors();
  const { sessions, ghostScore, streak, focusMinutes } = useGhost();
  const today = new Date();
  const days = Array.from({ length: 7 }, (_, index) => { const date = new Date(today); date.setDate(today.getDate() - (6 - index)); const key = getDayKey(date); const daySessions = sessions.filter((session) => getDayKey(new Date(session.completedAt)) === key); return { label: dayNames[date.getDay()], minutes: Math.round(daySessions.reduce((sum, item) => sum + item.focusedSeconds, 0) / 60), count: daySessions.length, today: index === 6 }; });
  const weekSessions = days.reduce((sum, day) => sum + day.count, 0);
  const weekMinutes = days.reduce((sum, day) => sum + day.minutes, 0);
  const completion = weekSessions === 0 ? 0 : 100;
  const maxMinutes = Math.max(...days.map((day) => day.minutes), 30);
  return <Screen>
    <TextLabel color={colors.primary}>INTELLIGENCE</TextLabel><Text style={[styles.title, { color: colors.foreground }]}>This week</Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>A quiet read on your consistency.</Text>
    <Panel accent style={{ marginTop: 24, backgroundColor: colors.secondary }}><View style={styles.scoreHeader}><View><TextLabel color={colors.primary}>GHOST SCORE</TextLabel><Text style={[styles.score, { color: colors.foreground }]}>{String(ghostScore).padStart(3, '0')}</Text></View><View style={[styles.scoreIcon, { backgroundColor: colors.primary }]}><Feather name="activity" size={24} color={colors.primaryForeground} /></View></View><View style={styles.scoreRule}><View style={[styles.scoreFill, { backgroundColor: colors.primary, width: ghostScore ? '68%' : '4%' }]} /></View><TextLabel color={colors.mutedForeground} size={10}>{ghostScore ? 'CONSISTENCY SIGNAL RISING' : 'COMPLETE A SESSION TO SET YOUR BASELINE'}</TextLabel></Panel>
    <SectionLabel>WEEKLY OUTPUT</SectionLabel>
    <View style={styles.metricGrid}><Panel style={styles.metric}><TextLabel color={colors.mutedForeground}>MISSIONS</TextLabel><Text style={[styles.metricValue, { color: colors.foreground }]}>{weekSessions}</Text><TextLabel color={colors.mutedForeground} size={9}>THIS WEEK</TextLabel></Panel><Panel style={styles.metric}><TextLabel color={colors.mutedForeground}>FOCUSED</TextLabel><Text style={[styles.metricValue, { color: colors.foreground }]}>{formatFocus(weekMinutes * 60)}</Text><TextLabel color={colors.mutedForeground} size={9}>THIS WEEK</TextLabel></Panel><Panel style={styles.metric}><TextLabel color={colors.mutedForeground}>COMPLETION</TextLabel><Text style={[styles.metricValue, { color: colors.foreground }]}>{completion}%</Text><TextLabel color={colors.mutedForeground} size={9}>MISSION RATE</TextLabel></Panel><Panel style={styles.metric}><TextLabel color={colors.mutedForeground}>STREAK</TextLabel><Text style={[styles.metricValue, { color: colors.foreground }]}>{streak}d</Text><TextLabel color={colors.mutedForeground} size={9}>CURRENT</TextLabel></Panel></View>
    <SectionLabel right={<TextLabel color={colors.mutedForeground} size={10}>{weekMinutes} MIN TOTAL</TextLabel>}>FOCUS RHYTHM</SectionLabel>
    <Panel><View style={styles.chart}>{days.map((day) => <View key={day.label} style={styles.barColumn}><View style={styles.barTrack}><View style={[styles.bar, { backgroundColor: day.minutes ? colors.primary : colors.accent, height: Math.max(8, (day.minutes / maxMinutes) * 110) }]} /></View><TextLabel color={day.today ? colors.foreground : colors.mutedForeground} size={9}>{day.label}</TextLabel>{day.count > 0 && <View style={[styles.dayDot, { backgroundColor: colors.success }]} />}</View>)}</View></Panel>
    <SectionLabel>GHOST SCORE FORMULA</SectionLabel>
    <Panel><View style={styles.formulaRow}><Feather name="clock" size={17} color={colors.primary} /><View style={{ flex: 1 }}><Text style={[styles.formulaTitle, { color: colors.foreground }]}>Focus time</Text><TextLabel color={colors.mutedForeground} size={10}>{focusMinutes} minutes logged / +2 per minute</TextLabel></View></View><View style={styles.formulaRow}><Feather name="repeat" size={17} color={colors.primary} /><View style={{ flex: 1 }}><Text style={[styles.formulaTitle, { color: colors.foreground }]}>Consistency</Text><TextLabel color={colors.mutedForeground} size={10}>{streak} day streak / +40 per day</TextLabel></View></View><View style={styles.formulaRow}><Feather name="check-circle" size={17} color={colors.primary} /><View style={{ flex: 1 }}><Text style={[styles.formulaTitle, { color: colors.foreground }]}>Completed missions</Text><TextLabel color={colors.mutedForeground} size={10}>{sessions.length} operations / +35 each</TextLabel></View></View></Panel>
  </Screen>;
}
const styles = StyleSheet.create({ title: { fontFamily: 'Inter_700Bold', fontSize: 30, letterSpacing: -1, marginTop: 8 }, subtitle: { fontFamily: 'Inter_400Regular', fontSize: 14, marginTop: 8 }, scoreHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, score: { fontFamily: 'Inter_700Bold', fontSize: 52, letterSpacing: -2, marginTop: 6 }, scoreIcon: { width: 53, height: 53, borderRadius: 17, alignItems: 'center', justifyContent: 'center' }, scoreRule: { height: 5, backgroundColor: '#252A31', borderRadius: 5, marginTop: 18, marginBottom: 10 }, scoreFill: { height: 5, borderRadius: 5 }, metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, metric: { width: '47%', minHeight: 100, justifyContent: 'space-between' }, metricValue: { fontFamily: 'Inter_700Bold', fontSize: 27, letterSpacing: -1, marginTop: 12 }, chart: { flexDirection: 'row', height: 155, alignItems: 'flex-end', justifyContent: 'space-between', paddingTop: 8 }, barColumn: { alignItems: 'center', justifyContent: 'flex-end', gap: 8, height: '100%' }, barTrack: { height: 114, width: 24, backgroundColor: '#15181D', borderRadius: 8, justifyContent: 'flex-end', overflow: 'hidden' }, bar: { width: 24, borderRadius: 8 }, dayDot: { width: 4, height: 4, borderRadius: 2 }, formulaRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: '#20242A' }, formulaTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 14, marginBottom: 5 } });
