import { Feather } from '@expo/vector-icons';
import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { useColors } from '@/hooks/useColors';
import { useGhost, formatFocus, initials } from '@/context/GhostContext';
import { Panel } from '@/components/Panel';
import { Screen, SectionLabel, TextLabel } from '@/components/Screen';

export default function SessionsScreen() {
  const colors = useColors();
  const { missions, sessions, activeSession, startSession } = useGhost();
  const start = (mission: typeof missions[number]) => { startSession(mission); router.push('/session'); };
  return <Screen>
    <View style={styles.header}><View><TextLabel color={colors.primary}>OPERATIONS</TextLabel><Text style={[styles.title, { color: colors.foreground }]}>Ghost Sessions</Text></View><Pressable onPress={() => router.push('/new-mission')} style={[styles.add, { backgroundColor: colors.primary }]}><Feather name="plus" size={17} color={colors.primaryForeground} /></Pressable></View>
    {activeSession && <Panel accent onPress={() => router.push('/session')} style={{ marginTop: 22, backgroundColor: colors.secondary }}><View style={styles.row}><View><TextLabel color={colors.primary}>ACTIVE CHANNEL</TextLabel><Text style={[styles.activeTitle, { color: colors.foreground }]}>{activeSession.missionTitle}</Text></View><Feather name="radio" size={20} color={colors.primary} /></View><TextLabel color={colors.mutedForeground} size={10}>RETURN TO SESSION / {activeSession.isPaused ? 'PAUSED' : 'RUNNING'}</TextLabel></Panel>}
    <SectionLabel right={<TextLabel color={colors.mutedForeground} size={10}>{sessions.length} COMPLETED</TextLabel>}>MISSION POOL</SectionLabel>
    {missions.length === 0 ? <Panel><View style={styles.empty}><Feather name="target" size={22} color={colors.primary} /><Text style={[styles.emptyTitle, { color: colors.foreground }]}>No missions in the pool</Text><Text style={[styles.emptyBody, { color: colors.mutedForeground }]}>Add one objective and run it until the room goes quiet.</Text><Pressable onPress={() => router.push('/new-mission')}><TextLabel color={colors.primary}>CREATE MISSION</TextLabel></Pressable></View></Panel> : missions.map((mission) => <Panel key={mission.id} onPress={() => start(mission)} style={styles.missionCard}><View style={[styles.initials, { backgroundColor: colors.secondary }]}><Text style={[styles.initialsText, { color: colors.primary }]}>{initials(mission.title)}</Text></View><View style={{ flex: 1 }}><Text style={[styles.missionTitle, { color: colors.foreground }]}>{mission.title}</Text><TextLabel color={colors.mutedForeground} size={10}>{mission.targetMinutes} MIN / {mission.detail || 'NO SECONDARY BRIEF'}</TextLabel></View><Feather name="play" size={17} color={colors.primary} /></Panel>)}
    <SectionLabel right={<TextLabel color={colors.mutedForeground} size={10}>PRIVATE ONLY</TextLabel>}>ACTIVITY LOG</SectionLabel>
    {sessions.length === 0 ? <View style={styles.emptyLog}><Feather name="archive" size={18} color={colors.mutedForeground} /><Text style={[styles.emptyBody, { color: colors.mutedForeground }]}>Complete your first session to build a private operator log.</Text></View> : sessions.map((session) => <View key={session.id} style={styles.logRow}><View style={[styles.check, { borderColor: colors.success }]}><Feather name="check" size={13} color={colors.success} /></View><View style={{ flex: 1 }}><Text style={[styles.missionTitle, { color: colors.foreground }]}>{session.missionTitle}</Text><TextLabel color={colors.mutedForeground} size={10}>{formatFocus(session.focusedSeconds)} FOCUSED / {session.checkpoints} CHECKPOINTS</TextLabel></View><TextLabel color={colors.mutedForeground} size={10}>{new Date(session.completedAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }).toUpperCase()}</TextLabel></View>)}
  </Screen>;
}
const styles = StyleSheet.create({ header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, title: { fontFamily: 'Inter_700Bold', fontSize: 28, letterSpacing: -0.8, marginTop: 8 }, add: { width: 42, height: 42, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }, activeTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 18, marginTop: 10 }, missionCard: { flexDirection: 'row', alignItems: 'center', gap: 13, marginBottom: 10 }, initials: { width: 42, height: 42, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, initialsText: { fontFamily: 'Inter_700Bold', fontSize: 12 }, missionTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 14, marginBottom: 6 }, empty: { alignItems: 'center', gap: 10, paddingVertical: 18 }, emptyTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 16 }, emptyBody: { fontFamily: 'Inter_400Regular', fontSize: 13, lineHeight: 20, textAlign: 'center', maxWidth: 260 }, emptyLog: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 15 }, logRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: '#20242A' }, check: { width: 29, height: 29, borderRadius: 9, borderWidth: 1, alignItems: 'center', justifyContent: 'center' } });
