import { Feather } from '@expo/vector-icons';
import React from 'react';
import { Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { useColors } from '@/hooks/useColors';
import { useGhost, formatTimer } from '@/context/GhostContext';
import { GhostMark } from '@/components/GhostMark';
import { Panel } from '@/components/Panel';
import { Screen, SectionLabel, TextLabel } from '@/components/Screen';

export default function SettingsScreen() {
  const colors = useColors();
  const { settings, updateSettings, activeSession, missions, sessions } = useGhost();
  const settingRow = (icon: React.ComponentProps<typeof Feather>['name'], title: string, detail: string, value: boolean, key: 'haptics' | 'sessionShield' | 'lowLight') => <View style={styles.settingRow}><View style={[styles.settingIcon, { backgroundColor: colors.secondary }]}><Feather name={icon} size={16} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={[styles.settingTitle, { color: colors.foreground }]}>{title}</Text><TextLabel color={colors.mutedForeground} size={10}>{detail}</TextLabel></View><Switch value={value} onValueChange={(next) => updateSettings({ [key]: next })} trackColor={{ false: colors.accent, true: colors.primary }} thumbColor={colors.foreground} /> </View>;
  return <Screen><View style={styles.header}><View><TextLabel color={colors.primary}>SYSTEM</TextLabel><Text style={[styles.title, { color: colors.foreground }]}>Settings</Text></View><GhostMark size={35} muted /></View>
    <SectionLabel>SESSION PROTOCOL</SectionLabel><Panel>{settingRow('shield', 'Session shield', 'Confirm before leaving an active operation', settings.sessionShield, 'sessionShield')}{settingRow('volume-2', 'Tactile signal', 'Subtle haptics for state changes', settings.haptics, 'haptics')}{settingRow('moon', 'Low light mode', 'Keep the command center dark', settings.lowLight, 'lowLight')}</Panel>
    <SectionLabel>LOCK SCREEN SIGNAL</SectionLabel><Panel style={{ backgroundColor: colors.secondary }}><View style={styles.widgetHeader}><TextLabel color={colors.primary}>GHOSTMODE / WIDGET PREVIEW</TextLabel><Feather name="smartphone" size={17} color={colors.mutedForeground} /></View><View style={styles.widget}><View><TextLabel color={colors.mutedForeground} size={9}>CURRENT MISSION</TextLabel><Text style={[styles.widgetMission, { color: colors.foreground }]}>{activeSession?.missionTitle ?? missions[0]?.title ?? 'NO ACTIVE MISSION'}</Text></View><Text style={[styles.widgetTimer, { color: colors.foreground }]}>{activeSession ? formatTimer(activeSession.remainingSeconds) : '--:--'}</Text></View><TextLabel color={colors.mutedForeground} size={10}>A minimal lock screen signal for your current operation.</TextLabel></Panel>
    <SectionLabel>DATA STATUS</SectionLabel><Panel><View style={styles.dataRow}><Feather name="lock" size={16} color={colors.success} /><View style={{ flex: 1 }}><Text style={[styles.settingTitle, { color: colors.foreground }]}>Local and private</Text><TextLabel color={colors.mutedForeground} size={10}>{missions.length} missions / {sessions.length} completed sessions</TextLabel></View><TextLabel color={colors.success} size={9}>ON DEVICE</TextLabel></View></Panel>
    <View style={styles.footer}><TextLabel color={colors.mutedForeground} size={9}>GHOSTMODE / BUILD 01</TextLabel><TextLabel color={colors.mutedForeground} size={9}>NO FEED. NO NOISE.</TextLabel></View>
  </Screen>;
}
const styles = StyleSheet.create({ header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, title: { fontFamily: 'Inter_700Bold', fontSize: 30, letterSpacing: -1, marginTop: 8 }, settingRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#20242A' }, settingIcon: { width: 34, height: 34, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, settingTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 14, marginBottom: 5 }, widgetHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, widget: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 20, padding: 15, borderRadius: 13, backgroundColor: '#090A0C', borderWidth: 1, borderColor: '#252A31' }, widgetMission: { fontFamily: 'Inter_600SemiBold', fontSize: 14, marginTop: 7, maxWidth: 175 }, widgetTimer: { fontFamily: 'Inter_700Bold', fontSize: 25, letterSpacing: -1 }, dataRow: { flexDirection: 'row', alignItems: 'center', gap: 12 }, footer: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 32, paddingBottom: 12 } });
